// Database of Raags with merged technical data.
const raags = [
  {
    id: 1,
    name: "Adana",
    thaat: "Asavari",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M P d N S'",
    avroh: "S' N d P M g R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Devotional, serious",
    pakad: "g M P d N, S' N d P M g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 8, 11",
    western_scale: "Aeolian (Natural Minor) - shares 0, 2, 3, 5, 7, 8, 10. Adana uses Shuddha Ni (11) where Aeolian uses Komal Ni (10).",
    similar_raags: "Darbari Kanada (shares some notes, but distinct chalan), Shahana Kanada"
  },
  {
    id: 2,
    name: "Alhaiya Bilawal",
    thaat: "Bilawal",
    jaati: "Shadav-Shadav",
    aaroh: "S R G P D N S'",
    avroh: "S' N D P G R S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Morning (9 AM-12 PM)",
    rasa: "Devotional, bright",
    pakad: "G P D N S', S' N D P G",
    bandishes: [],
    semitones: "0, 2, 4, 7, 9, 11 (Ma is omitted)",
    western_scale: "Ionian (Major) - if Ma (5) is considered omitted.",
    similar_raags: "Bilawal (parent scale, but Alhaiya omits Ma), Devgiri Bilawal"
  },
  {
    id: 3,
    name: "Anand Bhairav",
    thaat: "Bhairav",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r G M P D n S'",
    avroh: "S' n D P M G r S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, peaceful",
    pakad: "S r G M P, M G r S",
    bandishes: [],
    semitones: "0, 1, 4, 5, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Anand Bhairav uses Shuddha Ga (4) and Shuddha Dha (9) where Phrygian uses Komal Ga (3) and Komal Dha (8).",
    similar_raags: "Bhairav (parent scale, but Anand Bhairav uses Komal Ni)"
  },
  {
    id: 4,
    name: "Asavari",
    thaat: "Asavari",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M P d N S'",
    avroh: "S' N d P M g R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, serious",
    pakad: "g M P d N, N d P M g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 8, 11",
    western_scale: "Aeolian (Natural Minor) - shares 0, 2, 3, 5, 7, 8, 10. Asavari uses Shuddha Ni (11) where Aeolian uses Komal Ni (10).",
    similar_raags: "Jaunpuri (very close, but Jaunpuri uses Komal Ni), Komal Rishabh Asavari"
  },
  {
    id: 5,
    name: "Bageshree",
    thaat: "Kafi",
    jaati: "Audav-Shadav",
    aaroh: "S g M D n S'",
    avroh: "S' n D M g R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Devotional, romantic",
    pakad: "S g M D n, n D M g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 9, 10 (Re and Pa are omitted in Aroha)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Bageshree omits Pa (7) but otherwise matches Dorian.",
    similar_raags: "Kafi (parent scale, but Bageshree omits Re and Pa in Aroha), Nayaki Kanada"
  },
  {
    id: 6,
    name: "Basant",
    thaat: "Purvi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M^ P D N S'",
    avroh: "S' N D P M^ g R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late night/Early morning (3-6 AM)",
    rasa: "Romantic, spring mood",
    pakad: "g M^ P D N, S' N D P M^",
    bandishes: [],
    semitones: "0, 2, 3, 6, 7, 9, 11",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Basant uses Komal Ga (3) where Lydian uses Shuddha Ga (4).",
    similar_raags: "Purvi (parent scale, but Basant has a distinct mood)"
  },
  {
    id: 7,
    name: "Bhairav",
    thaat: "Bhairav",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r G M P D n S'",
    avroh: "S' n D P M G r S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, serious",
    pakad: "r G M P D, S' n D P M G r",
    bandishes: [],
    semitones: "0, 1, 4, 5, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Bhairav uses Shuddha Ga (4) and Shuddha Dha (9) where Phrygian uses Komal Ga (3) and Komal Dha (8).",
    similar_raags: "Ramkali (shares notes but different emphasis), Kalingda"
  },
  {
    id: 8,
    name: "Bhairavi",
    thaat: "Bhairavi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r g M P d n S'",
    avroh: "S' n d P M g r S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, compassionate",
    pakad: "S r g M P, n d P M g r",
    bandishes: [],
    semitones: "0, 1, 3, 5, 7, 8, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Exact match.",
    similar_raags: "Bilaskhani Todi (similar notes but different chalan)"
  },
  {
    id: 9,
    name: "Bhankar",
    thaat: "Marwa",
    jaati: "Shadav-Shadav",
    aaroh: "S r G M^ D N S'",
    avroh: "S' N D M^ G r S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Evening (6-9 PM)",
    rasa: "Serious, contemplative",
    pakad: "r G M^ D N, S' N D M^ G",
    bandishes: [],
    semitones: "0, 1, 4, 6, 9, 11 (Pa is omitted)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Bhankar uses Komal Re (1) where Lydian uses Shuddha Re (2), and omits Pa (7).",
    similar_raags: "Marwa (parent scale, shares notes but different emphasis)"
  },
  {
    id: 10,
    name: "Bhupali",
    thaat: "Kalyan",
    jaati: "Audav-Audav",
    aaroh: "S R G P D S'",
    avroh: "S' D P G R S",
    vadi: "Ga",
    samvadi: "Dha",
    time: "Evening (6-9 PM)",
    rasa: "Peaceful, meditative",
    pakad: "S R G P D, S' D P G R",
    bandishes: [],
    semitones: "0, 2, 4, 7, 9 (Ma and Ni are omitted)",
    western_scale: "Pentatonic Major (0, 2, 4, 7, 9) - Exact match for the 5 notes.",
    similar_raags: "Deskar (shares note omission, but different Thaat), Pahadi (folk, similar scale)"
  },
  {
    id: 11,
    name: "Bibhas",
    thaat: "Bhairav",
    jaati: "Audav-Audav",
    aaroh: "S G M P n S'",
    avroh: "S' n P M G S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, bright",
    pakad: "S G M P n, S' n P M G",
    bandishes: [],
    semitones: "0, 4, 5, 7, 10 (Re and Dha are omitted)",
    western_scale: "Mixolydian (0, 2, 4, 5, 7, 9, 10) - Bibhas omits Re (2) and Dha (9).",
    similar_raags: "Deshkar (similar note omission, but different Thaat and mood)"
  },
  {
    id: 12,
    name: "Bihag",
    thaat: "Bilawal",
    jaati: "Audav-Sampoorna",
    aaroh: "S G M P N S'",
    avroh: "S' N D P M G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, devotional",
    pakad: "S G M P N S', S' N D P M G",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11 (Re and Dha are omitted in Aroha)",
    western_scale: "Ionian (Major) - Exact match for the full scale.",
    similar_raags: "Yaman (shares Tivra Ma, but Bihag is Bilawal Thaat), Maru Bihag"
  },
  {
    id: 13,
    name: "Bilawal",
    thaat: "Bilawal",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P D N S'",
    avroh: "S' N D P M G R S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Morning (9 AM-12 PM)",
    rasa: "Devotional, bright",
    pakad: "S R G M P, P D N S'",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11",
    western_scale: "Ionian (Major) - Exact match.",
    similar_raags: "Shankara (shares notes, different emphasis), Shuddha Sarang"
  },
  {
    id: 14,
    name: "Chandrakauns",
    thaat: "Asavari",
    jaati: "Audav-Audav",
    aaroh: "S g M P n S'",
    avroh: "S' n P M g S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Mysterious, meditative",
    pakad: "S g M P n, S' n P M g",
    bandishes: [],
    semitones: "0, 3, 5, 7, 10 (Re and Dha are omitted)",
    western_scale: "Pentatonic Minor (0, 3, 5, 7, 10) - Exact match for the 5 notes.",
    similar_raags: "Malkauns (very similar scale, different Thaat and slightly different mood)"
  },
  {
    id: 15,
    name: "Darbari Kanada",
    thaat: "Asavari",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M P d N S'",
    avroh: "S' N d P, M P g M R S",
    vadi: "Re",
    samvadi: "Pa",
    time: "Late night (12-3 AM)",
    rasa: "Serious, majestic",
    pakad: "R g M g R S, g M P d N",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 8, 11",
    western_scale: "Aeolian (Natural Minor) - shares 0, 2, 3, 5, 7, 8, 10. Darbari uses Shuddha Ni (11) where Aeolian uses Komal Ni (10).",
    similar_raags: "Adana (shares notes, but Darbari has a distinct grave character), Shahana Kanada"
  },
  {
    id: 16,
    name: "Desh",
    thaat: "Khamaj",
    jaati: "Audav-Sampoorna",
    aaroh: "N S R M P N S'",
    avroh: "S' N D P M G R S",
    vadi: "Re",
    samvadi: "Pa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Devotional, patriotic",
    pakad: "N S R M P, N S' N D P",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11 (Ga and Dha omitted in Aroha)",
    western_scale: "Ionian (Major) - Exact match for the full scale.",
    similar_raags: "Tilang (shares Khamaj Thaat, but different note emphasis)"
  },
  {
    id: 17,
    name: "Deskar",
    thaat: "Bilawal",
    jaati: "Audav-Shadav",
    aaroh: "S R M P N S'",
    avroh: "S' N P M R G R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Devotional, peaceful",
    pakad: "S R M P N, S' N P M R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 11 (Ga and Dha omitted in Aroha, Dha is omitted in Avroha)",
    western_scale: "Ionian (Major) - if Ga (4) and Dha (9) are considered omitted.",
    similar_raags: "Bhupali (similar note omission, but different Thaat and mood)"
  },
  {
    id: 18,
    name: "Devgiri Bilawal",
    thaat: "Bilawal",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P, D N S'",
    avroh: "S' N D P, M G R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Morning (9 AM-12 PM)",
    rasa: "Devotional, bright",
    pakad: "R G M P D N, S' N D P M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11",
    western_scale: "Ionian (Major) - Exact match.",
    similar_raags: "Alhaiya Bilawal (shares Bilawal Thaat)"
  },
  {
    id: 19,
    name: "Durga",
    thaat: "Bilawal",
    jaati: "Audav-Audav",
    aaroh: "S R M P D S'",
    avroh: "S' D P M R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Evening (6-9 PM)",
    rasa: "Devotional, heroic",
    pakad: "S R M P D, S' D P M R",
    bandishes: [],
    semitones: "0, 2, 5, 7, 9 (Ga and Ni are omitted)",
    western_scale: "Pentatonic Major (0, 2, 4, 7, 9) - Durga omits Ga (4) but otherwise matches.",
    similar_raags: "Bhupali (shares Audav Jaati and note omission, different Thaat)"
  },
  {
    id: 20,
    name: "Gaud Malhar",
    thaat: "Bilawal",
    jaati: "Shadav-Shadav",
    aaroh: "S R G M D N S'",
    avroh: "S' N D M G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Monsoon, evening (6-9 PM)",
    rasa: "Romantic, rain mood",
    pakad: "S R G M D N, S' N D M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 9, 11 (Pa is omitted)",
    western_scale: "Ionian (Major) - if Pa (7) is considered omitted.",
    similar_raags: "Miyan ki Malhar (shares Malhar Ang, but different note usage)"
  },
  {
    id: 21,
    name: "Gaud Sarang",
    thaat: "Bilawal",
    jaati: "Shadav-Shadav",
    aaroh: "S R M P D N S'",
    avroh: "S' N D P M R S",
    vadi: "Re",
    samvadi: "Pa",
    time: "Morning (9 AM-12 PM)",
    rasa: "Bright, joyful",
    pakad: "S R M P D N, S' N D P M R",
    bandishes: [],
    semitones: "0, 2, 5, 7, 9, 11 (Ga is omitted)",
    western_scale: "Ionian (Major) - if Ga (4) is considered omitted.",
    similar_raags: "Shuddha Sarang (shares Sarang Ang, but Gaud Sarang has distinct movements)"
  },
  {
    id: 22,
    name: "Gorakh Kalyan",
    thaat: "Kalyan",
    jaati: "Shadav-Shadav",
    aaroh: "S R G M^ P N S'",
    avroh: "S' N P M^ G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Meditative, serious",
    pakad: "S R G M^ P N, S' N P M^ G R",
    bandishes: [],
    semitones: "0, 2, 4, 6, 7, 11 (Dha is omitted)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Gorakh Kalyan omits Dha (9).",
    similar_raags: "Yaman (shares Kalyan Thaat, but Gorakh Kalyan omits Dha and has a different emphasis)"
  },
  {
    id: 23,
    name: "Gujari Todi",
    thaat: "Todi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r g M^ P D n S'",
    avroh: "S' n D P M^ g r S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, melancholic",
    pakad: "r g M^ P D n, S' n D P M^ g",
    bandishes: [],
    semitones: "0, 1, 3, 6, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Gujari Todi uses Tivra Ma (6) where Phrygian uses Shuddha Ma (5), Shuddha Dha (9) where Phrygian uses Komal Dha (8).",
    similar_raags: "Miyan ki Todi (shares Todi Thaat, but Gujari Todi is more melancholic)"
  },
  {
    id: 24,
    name: "Hameer",
    thaat: "Kalyan",
    jaati: "Audav-Shadav",
    aaroh: "S G M^ D N S'",
    avroh: "S' N D M^ G R S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Late night (12-3 AM)",
    rasa: "Devotional, serious",
    pakad: "S G M^ D N, S' N D M^ G",
    bandishes: [],
    semitones: "0, 2, 4, 6, 9, 11 (Re and Pa are omitted in Aroha, Pa is omitted in Avroha)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Hameer omits Pa (7).",
    similar_raags: "Kedar (shares Kalyan Thaat and Tivra Ma, but different melodic emphasis)"
  },
  {
    id: 25,
    name: "Hansadhwani",
    thaat: "Bilawal",
    jaati: "Audav-Audav",
    aaroh: "S R G P N S'",
    avroh: "S' N P G R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Evening (6-9 PM)",
    rasa: "Joyful, bright",
    pakad: "S R G P N, S' N P G R",
    bandishes: [],
    semitones: "0, 2, 4, 7, 11 (Ma and Dha are omitted)",
    western_scale: "Pentatonic Major (0, 2, 4, 7, 9) - Hansadhwani uses Shuddha Ni (11) where Pentatonic Major omits it, and omits Ma (5) and Dha (9).",
    similar_raags: "Shankara (shares note omission, but different character)"
  },
  {
    id: 26,
    name: "Hemant",
    thaat: "Bilawal",
    jaati: "Shadav-Shadav",
    aaroh: "S R G M P D S'",
    avroh: "S' D P M G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Contemplative, winter mood",
    pakad: "S R G M P D, S' D P M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9 (Ni is omitted)",
    western_scale: "Ionian (Major) - if Ni (11) is considered omitted.",
    similar_raags: "Durga (shares note omission, but different character)"
  },
  {
    id: 27,
    name: "Jaijaiwanti",
    thaat: "Khamaj",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P n D N S'",
    avroh: "S' N D n P M G R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, devotional",
    pakad: "G M P n D N S', S' N D n P M G",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 10, 11 (uses both Komal Ni and Shuddha Ni)",
    western_scale: "None (uses both forms of Ni, which is uncommon in basic Western modes)",
    similar_raags: "Khamaj (parent scale, but Jaijaiwanti uses both Nis)"
  },
  {
    id: 28,
    name: "Jaunpuri",
    thaat: "Asavari",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M P D n S'",
    avroh: "S' n D P M g R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, melancholic",
    pakad: "S R g M P D n, S' n D P M g R",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 9, 10",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Exact match.",
    similar_raags: "Asavari (very close, but Jaunpuri uses Komal Ni), Komal Rishabh Asavari"
  },
  {
    id: 29,
    name: "Jhinjhoti",
    thaat: "Khamaj",
    jaati: "Audav-Shadav",
    aaroh: "S G M D n S'",
    avroh: "S' n D M G R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Light, playful",
    pakad: "S G M D n, S' n D M G",
    bandishes: [],
    semitones: "0, 2, 4, 5, 9, 10 (Re and Pa are omitted in Aroha, Pa is omitted in Avroha)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Jhinjhoti uses Shuddha Ga (4) where Dorian uses Komal Ga (3), and omits Pa (7).",
    similar_raags: "Desh (shares Khamaj Thaat, but different note emphasis)"
  },
  {
    id: 30,
    name: "Jog",
    thaat: "Kafi",
    jaati: "Audav-Audav",
    aaroh: "N S g M D S'",
    avroh: "S' D M g R g S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Evening (6-9 PM)",
    rasa: "Meditative, serious",
    pakad: "N S g M D, S' D M g R g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 9, 11 (Pa and Komal Ni are omitted)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Jog omits Pa (7) and uses Shuddha Ni (11) where Dorian uses Komal Ni (10).",
    similar_raags: "Bageshree (shares Kafi Thaat and Komal Ga, but different note omission)"
  },
  {
    id: 31,
    name: "Kafi",
    thaat: "Kafi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M P D n S'",
    avroh: "S' n D P M g R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, light",
    pakad: "g M P D n S', S' n D P M g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 9, 10",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Exact match.",
    similar_raags: "Bageshree (parent scale, but Bageshree omits Re and Pa in Aroha)"
  },
  {
    id: 32,
    name: "Kalingda",
    thaat: "Kafi",
    jaati: "Audav-Shadav",
    aaroh: "S g M P n S'",
    avroh: "S' n P M g R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Mysterious, meditative",
    pakad: "S g M P n, S' n P M g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 10 (Re and Dha are omitted in Aroha, Dha is omitted in Avroha)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Kalingda omits Dha (9).",
    similar_raags: "Bhairav (shares mood, but different Thaat and note usage)"
  },
  {
    id: 33,
    name: "Kamod",
    thaat: "Kalyan",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M^ P D N S'",
    avroh: "S' N D P M^ G R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, peaceful",
    pakad: "G M^ P D N S', S' N D P M^ G",
    bandishes: [],
    semitones: "0, 2, 4, 6, 7, 9, 11",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Exact match.",
    similar_raags: "Kedar (shares Kalyan Thaat and Tivra Ma), Yaman (shares Kalyan Thaat)"
  },
  {
    id: 34,
    name: "Kedar",
    thaat: "Kalyan",
    jaati: "Shadav-Shadav",
    aaroh: "S R G M^ P N S'",
    avroh: "S' N P M^ G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Devotional, peaceful",
    pakad: "S R G M^ P N, S' N P M^ G R",
    bandishes: [],
    semitones: "0, 2, 4, 6, 7, 11 (Dha is omitted)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Kedar omits Dha (9).",
    similar_raags: "Hameer (shares Kalyan Thaat and Tivra Ma), Yaman (shares Kalyan Thaat)"
  },
  {
    id: 35,
    name: "Khamaj",
    thaat: "Khamaj",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P D n S'",
    avroh: "S' n D P M G R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, light",
    pakad: "G M P D n S', S' n D P M G",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 10",
    western_scale: "Mixolydian (0, 2, 4, 5, 7, 9, 10) - Exact match.",
    similar_raags: "Desh (shares Khamaj Thaat), Tilang (shares Khamaj Thaat)"
  },
  {
    id: 36,
    name: "Komal Rishabh Asavari",
    thaat: "Asavari",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r g M P d N S'",
    avroh: "S' N d P M g r S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, melancholic",
    pakad: "S r g M P d N, S' N d P M g r",
    bandishes: [],
    semitones: "0, 1, 3, 5, 7, 8, 11",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Komal Rishabh Asavari uses Shuddha Ni (11) where Phrygian uses Komal Ni (10).",
    similar_raags: "Asavari (shares Thaat, but Komal Rishabh Asavari uses Komal Re)"
  },
  {
    id: 37,
    name: "Lalit",
    thaat: "Purvi",
    jaati: "Shadav-Shadav",
    aaroh: "S r G M^ D n S'",
    avroh: "S' n D M^ G r S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Early morning (3-6 AM)",
    rasa: "Devotional, serious",
    pakad: "r G M^ D n S', S' n D M^ G r",
    bandishes: [],
    semitones: "0, 1, 4, 6, 9, 10 (Pa is omitted)",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Lalit uses Shuddha Ga (4) where Phrygian uses Komal Ga (3), Tivra Ma (6) where Phrygian uses Shuddha Ma (5), Shuddha Dha (9) where Phrygian uses Komal Dha (8), and omits Pa (7).",
    similar_raags: "Purvi (parent scale, but Lalit omits Pa and has a unique Tivra Ma usage)"
  },
  {
    id: 38,
    name: "Lankadahan Sarang",
    thaat: "Bilawal",
    jaati: "Shadav-Shadav",
    aaroh: "S R M P D N S'",
    avroh: "S' N D P M R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (9 AM-12 PM)",
    rasa: "Heroic, bright",
    pakad: "S R M P D N, S' N D P M R",
    bandishes: [],
    semitones: "0, 2, 5, 7, 9, 11 (Ga is omitted)",
    western_scale: "Ionian (Major) - if Ga (4) is considered omitted.",
    similar_raags: "Shuddha Sarang (shares Sarang Ang, but different emphasis)"
  },
  {
    id: 39,
    name: "Malkauns",
    thaat: "Bhairavi",
    jaati: "Audav-Audav",
    aaroh: "S g M d n S'",
    avroh: "S' n d M g S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Serious, meditative",
    pakad: "g M d n S', S' n d M g",
    bandishes: [],
    semitones: "0, 3, 5, 8, 10 (Re and Pa are omitted)",
    western_scale: "Pentatonic Minor (0, 3, 5, 7, 10) - Malkauns uses Komal Dha (8) where Pentatonic Minor uses Shuddha Dha (7).",
    similar_raags: "Chandrakauns (very similar scale, different Thaat and slightly different mood)"
  },
  {
    id: 40,
    name: "Maru Bihag",
    thaat: "Kalyan",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M^ P D N S'",
    avroh: "S' N D P M^ G R S",
    vadi: "Re",
    samvadi: "Pa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, devotional",
    pakad: "R G M^ P D N S', S' N D P M^ G R",
    bandishes: [],
    semitones: "0, 2, 4, 6, 7, 9, 11",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Exact match.",
    similar_raags: "Yaman (shares Kalyan Thaat and Tivra Ma, but Maru Bihag has a distinct Bihag Ang)"
  },
  {
    id: 41,
    name: "Marwa",
    thaat: "Marwa",
    jaati: "Shadav-Shadav",
    aaroh: "S r G M^ D N S'",
    avroh: "S' N D M^ G r S",
    vadi: "Re",
    samvadi: "Pa",
    time: "Evening (6-9 PM)",
    rasa: "Serious, contemplative",
    pakad: "r G M^ D N S', S' N D M^ G r",
    bandishes: [],
    semitones: "0, 1, 4, 6, 9, 11 (Pa is omitted)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Marwa uses Komal Re (1) where Lydian uses Shuddha Re (2), and omits Pa (7).",
    similar_raags: "Puriya (shares Marwa Thaat and Komal Re, Tivra Ma), Sohini"
  },
  {
    id: 42,
    name: "Megh",
    thaat: "Kafi",
    jaati: "Shadav-Shadav",
    aaroh: "S R g M P N S'",
    avroh: "S' N P M g R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Monsoon, evening (6-9 PM)",
    rasa: "Romantic, rain mood",
    pakad: "S R g M P N, S' N P M g R",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 11 (Dha is omitted)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Megh uses Shuddha Ni (11) where Dorian uses Komal Ni (10), and omits Dha (9).",
    similar_raags: "Miyan ki Malhar (shares Malhar Ang, but different note usage)"
  },
  {
    id: 43,
    name: "Miyan ki Malhar",
    thaat: "Kafi",
    jaati: "Shadav-Shadav",
    aaroh: "S R g M P N S'",
    avroh: "S' N P g M R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Monsoon, evening (6-9 PM)",
    rasa: "Romantic, rain mood",
    pakad: "S R g M P N, N P g M R",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 11 (Dha is omitted)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Miyan ki Malhar uses Shuddha Ni (11) where Dorian uses Komal Ni (10), and omits Dha (9).",
    similar_raags: "Megh (shares Malhar Ang, but different note usage)"
  },
  {
    id: 44,
    name: "Miyan ki Todi",
    thaat: "Todi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r g M^ P D n S'",
    avroh: "S' n D P M^ g r S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, melancholic",
    pakad: "r g M^ P D n, S' n D P M^ g r",
    bandishes: [],
    semitones: "0, 1, 3, 6, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Miyan ki Todi uses Tivra Ma (6) where Phrygian uses Shuddha Ma (5), Shuddha Dha (9) where Phrygian uses Komal Dha (8).",
    similar_raags: "Gujari Todi (shares Todi Thaat, but Miyan ki Todi is more prominent)"
  },
  {
    id: 45,
    name: "Multani",
    thaat: "Todi",
    jaati: "Shadav-Shadav",
    aaroh: "S r g M^ D n S'",
    avroh: "S' n D M^ g r S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Evening (6-9 PM)",
    rasa: "Serious, contemplative",
    pakad: "S r g M^ D n, S' n D M^ g r",
    bandishes: [],
    semitones: "0, 1, 3, 6, 9, 10 (Pa is omitted)",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Multani uses Tivra Ma (6) where Phrygian uses Shuddha Ma (5), Shuddha Dha (9) where Phrygian uses Komal Dha (8), and omits Pa (7).",
    similar_raags: "Todi (shares Todi Thaat, but Multani has distinct emphasis on Tivra Ma)"
  },
  {
    id: 46,
    name: "Nat Bhairav",
    thaat: "Bhairav",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r G M P D N S'",
    avroh: "S' N D P M G r S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, bright",
    pakad: "S r G M P D N, S' N D P M G r",
    bandishes: [],
    semitones: "0, 1, 4, 5, 7, 9, 11",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Nat Bhairav uses Shuddha Ga (4) where Phrygian uses Komal Ga (3), Shuddha Dha (9) where Phrygian uses Komal Dha (8), and Shuddha Ni (11) where Phrygian uses Komal Ni (10).",
    similar_raags: "Bhairav (shares Bhairav Thaat, but Nat Bhairav has a brighter feel)"
  },
  {
    id: 47,
    name: "Nayaki Kanada",
    thaat: "Kafi",
    jaati: "Shadav-Sampoorna",
    aaroh: "S g M P D n S'",
    avroh: "S' n D P M g R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Late night (12-3 AM)",
    rasa: "Romantic, melancholic",
    pakad: "S g M P D n, S' n D P M g",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 9, 10 (Re is omitted in Aroha)",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Exact match.",
    similar_raags: "Bageshree (shares Kafi Thaat and Komal Ga), Darbari Kanada (shares Kanada Ang)"
  },
  {
    id: 48,
    name: "Pancham",
    thaat: "Bilawal",
    jaati: "Shadav-Shadav",
    aaroh: "S R G M D N S'",
    avroh: "S' N D M G R S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "[unknown]",
    rasa: "[unknown]",
    pakad: "[unknown]",
    bandishes: [],
    semitones: "0, 2, 4, 5, 9, 11 (Pa is omitted)",
    western_scale: "Ionian (Major) - if Pa (7) is considered omitted.",
    similar_raags: "(Information is scarce, similar to Gaud Malhar in note omission but distinct)"
  },
  {
    id: 49,
    name: "Puriya",
    thaat: "Marwa",
    jaati: "Shadav-Sampoorna",
    aaroh: "S r G M^ D N S'",
    avroh: "S' N D P M^ G r S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Evening (6-9 PM)",
    rasa: "Romantic, contemplative",
    pakad: "r G M^ D N S', S' N D P M^ G r",
    bandishes: [],
    semitones: "0, 1, 4, 6, 7, 9, 11 (Pa is omitted in Aroha)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Puriya uses Komal Re (1) where Lydian uses Shuddha Re (2).",
    similar_raags: "Marwa (shares Marwa Thaat and Komal Re, Tivra Ma), Puriya Dhanashree"
  },
  {
    id: 50,
    name: "Puriya Dhanashree",
    thaat: "Purvi",
    jaati: "Shadav-Shadav",
    aaroh: "S r G M^ P N S'",
    avroh: "S' N P M^ G r S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Devotional, peaceful",
    pakad: "r G M^ P N S', S' N P M^ G r",
    bandishes: [],
    semitones: "0, 1, 4, 6, 7, 11 (Dha is omitted)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Puriya Dhanashree uses Komal Re (1) where Lydian uses Shuddha Re (2), and omits Dha (9).",
    similar_raags: "Puriya (shares Tivra Ma and Komal Re, but different Thaat), Shree"
  },
  {
    id: 51,
    name: "Rageshree",
    thaat: "Kafi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R g M P D N S'",
    avroh: "S' N D P M g R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Romantic, devotional",
    pakad: "S R g M P D N, S' N D P M g R",
    bandishes: [],
    semitones: "0, 2, 3, 5, 7, 9, 11",
    western_scale: "Dorian (0, 2, 3, 5, 7, 9, 10) - Rageshree uses Shuddha Ni (11) where Dorian uses Komal Ni (10).",
    similar_raags: "Kafi (parent scale, but Rageshree has a distinct melodic emphasis)"
  },
  {
    id: 52,
    name: "Ramkali",
    thaat: "Bhairav",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r G M P D n S'",
    avroh: "S' n D P M G r S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, bright",
    pakad: "S r G M P D n, S' n D P M G r",
    bandishes: [],
    semitones: "0, 1, 4, 5, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Ramkali uses Shuddha Ga (4) where Phrygian uses Komal Ga (3), Shuddha Dha (9) where Phrygian uses Komal Dha (8).",
    similar_raags: "Bhairav (shares Bhairav Thaat, but Ramkali has a more expansive character)"
  },
  {
    id: 53,
    name: "Shankara",
    thaat: "Bilawal",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P D N S'",
    avroh: "S' N D P M G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Morning (9 AM-12 PM)",
    rasa: "Devotional, bright",
    pakad: "S R G M P D N, S' N D P M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11",
    western_scale: "Ionian (Major) - Exact match.",
    similar_raags: "Bilawal (parent scale, but Shankara has a distinct heroic character)"
  },
  {
    id: 54,
    name: "Shree",
    thaat: "Purvi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r G M^ P D n S'",
    avroh: "S' n D P M^ G r S",
    vadi: "Pa",
    samvadi: "Sa",
    time: "Evening (6-9 PM)",
    rasa: "Devotional, serious",
    pakad: "r G M^ P D n S', S' n D P M^ G r",
    bandishes: [],
    semitones: "0, 1, 4, 6, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Shree uses Shuddha Ga (4) where Phrygian uses Komal Ga (3), Tivra Ma (6) where Phrygian uses Shuddha Ma (5), Shuddha Dha (9) where Phrygian uses Komal Dha (8).",
    similar_raags: "Puriya Dhanashree (shares Purvi Thaat and similar notes)"
  },
  {
    id: 55,
    name: "Shuddha Nat",
    thaat: "Bilawal",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P D N S'",
    avroh: "S' N D P M G R S",
    vadi: "Ma",
    samvadi: "Sa",
    time: "Evening (6-9 PM)",
    rasa: "Peaceful, meditative",
    pakad: "S R G M P D N, S' N D P M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11",
    western_scale: "Ionian (Major) - Exact match.",
    similar_raags: "Bilawal (parent scale, but Shuddha Nat has a distinct melodic emphasis)"
  },
  {
    id: 56,
    name: "Shuddha Sarang",
    thaat: "Bilawal",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S R G M P D N S'",
    avroh: "S' N D P M G R S",
    vadi: "Re",
    samvadi: "Pa",
    time: "Morning (9 AM-12 PM)",
    rasa: "Bright, joyful",
    pakad: "S R G M P D N, S' N D P M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 9, 11",
    western_scale: "Ionian (Major) - Exact match.",
    similar_raags: "Gaud Sarang (shares Sarang Ang, but different emphasis)"
  },
  {
    id: 57,
    name: "Sohini",
    thaat: "Marwa",
    jaati: "Shadav-Shadav",
    aaroh: "S r G M^ D N S'",
    avroh: "S' N D M^ G r S",
    vadi: "Dha",
    samvadi: "Ga",
    time: "Late night/Early morning (3-6 AM)",
    rasa: "Romantic, longing",
    pakad: "r G M^ D N S', S' N D M^ G r",
    bandishes: [],
    semitones: "0, 1, 4, 6, 9, 11 (Pa is omitted)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Sohini uses Komal Re (1) where Lydian uses Shuddha Re (2), and omits Pa (7).",
    similar_raags: "Marwa (shares Marwa Thaat and Komal Re, Tivra Ma), Puriya (shares note omission)"
  },
  {
    id: 58,
    name: "Tilang",
    thaat: "Khamaj",
    jaati: "Shadav-Shadav",
    aaroh: "S R G M P n S'",
    avroh: "S' n P M G R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Late evening (9 PM-12 AM)",
    rasa: "Devotional, peaceful",
    pakad: "S R G M P n, S' n P M G R",
    bandishes: [],
    semitones: "0, 2, 4, 5, 7, 10 (Dha is omitted)",
    western_scale: "Mixolydian (0, 2, 4, 5, 7, 9, 10) - Tilang omits Dha (9).",
    similar_raags: "Desh (shares Khamaj Thaat, but Tilang omits Dha)"
  },
  {
    id: 59,
    name: "Todi",
    thaat: "Todi",
    jaati: "Sampoorna-Sampoorna",
    aaroh: "S r g M^ P D n S'",
    avroh: "S' n D P M^ g r S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Morning (6-9 AM)",
    rasa: "Devotional, melancholic",
    pakad: "r g M^ P D n, S' n D P M^ g r",
    bandishes: [],
    semitones: "0, 1, 3, 6, 7, 9, 10",
    western_scale: "Phrygian (0, 1, 3, 5, 7, 8, 10) - Todi uses Tivra Ma (6) where Phrygian uses Shuddha Ma (5), Shuddha Dha (9) where Phrygian uses Komal Dha (8).",
    similar_raags: "Miyan ki Todi (shares Todi Thaat, but Miyan ki Todi is more prominent), Gujari Todi"
  },
  {
    id: 60,
    name: "Yaman",
    thaat: "Kalyan",
    jaati: "Shadav-Sampoorna",
    aaroh: "N R G M^ D N S'",
    avroh: "S' N D P M^ G R S",
    vadi: "Ga",
    samvadi: "Ni",
    time: "Evening (6-9 PM)",
    rasa: "Romantic, peaceful",
    pakad: "N R G M^, D N S'",
    bandishes: [],
    semitones: "0, 2, 4, 6, 7, 9, 11 (Pa is omitted in Aroha)",
    western_scale: "Lydian (0, 2, 4, 6, 7, 9, 11) - Exact match for the full scale.",
    similar_raags: "Kalyan (parent scale, but Yaman is the most common and distinct), Maru Bihag, Kedar"
  }
];